### ISSUE TITLE
Shoes try on web sdk doesn't work at all.

### ISSUE THREAD

**Issue by saadsb20** [DeepARSDK/shoetryon-web-js#1]
After following the Readme instructions, the web implementation doesn't work and It stays loading :
![image](https://user-images.githubusercontent.com/74252238/188628115-aff407cc-cb3c-4290-96cd-66e77ca606ea.png)

And it gives me this Error : 
![image](https://user-images.githubusercontent.com/74252238/188628357-08c40533-e82f-43c2-8533-7d3d02ce5764.png)

**Comment by DishoD** [comment]
It seems like your python server crashes for some reason. I don't have any information to be able to debug this.
The python server is not part of DeepAR Web SDK. You can try serving the web app with some other server or try to debug why is your python server crashing. First question I would ask is on what request is it crashing?

**Comment by saadsb20** [comment]
As you said, It wasn't a problem with the DeepAR Web SDK, I tried to run It with another server and It works very well.
