### ISSUE TITLE
how to load my own 3d shoe model 

### ISSUE THREAD

**Issue by lohithkumarr95** [DeepARSDK/shoetryon-web-js#3]
Hi All,

I am able to clone and the run project and everything works fine. But if i have to load my own 3d model or  fbx file how do i achieve it?

Can someone help. Thanks in advance.

**Comment by DishoD** [comment]
The workflow for testing your own 3D shoes goes like this:

1. Create AR Shoe Try-On experience in DeepAR Studio (see [here](https://docs.deepar.ai/deep-ar-studio/tutorials/shoe-try-on-quick-setup)).
2. Export the effect file DeepAR Studio.
3. Load the effect file into DeepAR Web SDK.

The effect used in this example is `effects/Shoe_PBR`.
