### ISSUE TITLE
React.js implementation

### ISSUE THREAD

**Issue by ismailajizou** [DeepARSDK/shoetryon-web-js#4]
I am trying to implement this feature in a react app. Is there a template or docs for that.

**Comment by DishoD** [comment]
You can install [DeepAR Web SDK](https://www.npmjs.com/package/deepar) from npm.
The rest is implementing react app as usual.

This is a high level overview of how to use DeepAR in react component:
1. Signup at [developer.deepar.ai](https://developer.deepar.ai/) and create a Web project to get a license key.
2. Install [DeepAR Web](https://www.npmjs.com/package/deepar) with NPM.
3. Import DeepAR class and foot tracking models and assets (see [README](https://www.npmjs.com/package/deepar) on npm page of our official [API reference](https://s3.eu-west-1.amazonaws.com/sdk.developer.deepar.ai/doc/web/index.html)).
4. Create canvas inside your react component.
5. Initialize DeepAR with foot tracking and the canvas element.
6. Load the shoes effect in DeepAR with `switchEffect`. You can use the one provided in this example or create your own DeepAR effect with your own 3D shoes model (see [here](https://docs.deepar.ai/deep-ar-studio/tutorials/shoe-try-on-quick-setup)).
